<a href="https://colab.research.google.com/github/dabster108/K-Nearest-Neighbor-KNN-Algorithm-for-Machine-Learning/blob/main/Knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

knn - k nearest neighbour supervised Learning
Regressor vs Classifier
regressor - past data  
classifier - previously there will be category and it determines in which categeory does the data belongs


non -parametric - doesnot make assumption
parametric - interpretable
euclidean distance
knn - non parametric
Supervised Learning

Independednt variable and Dependent Variable


In [ ]:
import pandas as pd
import numpy as np
import random

#set random seed for reproducibility
np.random.seed(42)

#generate data
num_rows = 100
data ={
    'User Id': range(1, num_rows +1),
    'Gender': np.random.choice(['Male', 'Female'], num_rows),
    'Age': np.random.randint(18, 65, num_rows),
    'Estimated Salary':np.random.randint(20000, 2000000, num_rows),
    'Purchased': np.random.randint(0, 2, num_rows)
}
#create dataframe
df = pd.DataFrame(data)



In [ ]:
print(df)

    User Id  Gender  Age  Estimated Salary  Purchased
0         1    Male   35            980061          1
1         2  Female   43            462296          1
2         3    Male   61            129556          0
3         4    Male   51           1595557          0
4         5    Male   27           1950267          1
..      ...     ...  ...               ...        ...
95       96  Female   39           1935631          1
96       97  Female   45             42671          0
97       98  Female   19           1486976          1
98       99  Female   59           1424104          0
99      100    Male   62           1679066          1

[100 rows x 5 columns]


In [ ]:
df.to_csv('dataset.csv', index=False)

In [ ]:
#import the dataset
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset.csv')
print(df)
df.head(5)


    User Id  Gender  Age  Estimated Salary  Purchased
0         1    Male   35            980061          1
1         2  Female   43            462296          1
2         3    Male   61            129556          0
3         4    Male   51           1595557          0
4         5    Male   27           1950267          1
..      ...     ...  ...               ...        ...
95       96  Female   39           1935631          1
96       97  Female   45             42671          0
97       98  Female   19           1486976          1
98       99  Female   59           1424104          0
99      100    Male   62           1679066          1

[100 rows x 5 columns]


User Id  Gender  Age  Estimated Salary  Purchased
0        1    Male   35            980061          1
1        2  Female   43            462296          1
2        3    Male   61            129556          0
3        4    Male   51           1595557          0
4        5    Male   27           1950267          1

Steps

- Data Preprocessing
- Fitting Knn to the traning set
- Predicting the result
- Test accuracy of the result
- visualise the result

In [ ]:
# importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



In [ ]:
data_set = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset.csv')
data_set

User Id  Gender  Age  Estimated Salary  Purchased
0         1    Male   35            980061          1
1         2  Female   43            462296          1
2         3    Male   61            129556          0
3         4    Male   51           1595557          0
4         5    Male   27           1950267          1
..      ...     ...  ...               ...        ...
95       96  Female   39           1935631          1
96       97  Female   45             42671          0
97       98  Female   19           1486976          1
98       99  Female   59           1424104          0
99      100    Male   62           1679066          1

[100 rows x 5 columns]

In [ ]:
x = data_set.iloc[:, [2,3]].values # location of usage of age and the estimated salary
y = data_set.iloc[:, 4].values  #location of the purachased row

In [ ]:
display(x)
display(y)

array([[     35,  980061],
       [     43,  462296],
       [     61,  129556],
       [     51, 1595557],
       [     27, 1950267],
       [     53,  787595],
       [     31,  220235],
       [     48,   45939],
       [     32, 1221482],
       [     25,  562335],
       [     31, 1356825],
       [     40,   95766],
       [     57,  428923],
       [     38, 1483768],
       [     33,  588550],
       [     62,  407261],
       [     35,  830208],
       [     64,  705440],
       [     41, 1721240],
       [     43, 1004346],
       [     42, 1523165],
       [     62,  157848],
       [     58,  637075],
       [     46,  147948],
       [     32, 1647880],
       [     62,  422690],
       [     18,  519046],
       [     42,  471269],
       [     24,   41959],
       [     26, 1729466],
       [     41, 1818792],
       [     18, 1974109],
       [     61, 1858756],
       [     25,  248576],
       [     41, 1035602],
       [     28, 1606409],
       [     34,  934091],
 

array([1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1])

In [ ]:
# mean mode median average salary
data_set['Estimated Salary'].mean()

947911.37

In [ ]:
data_set['Estimated Salary'].median()
data_set['Estimated Salary'].mode()

0       41959
1       42671
2       45939
3       59353
4       81087
       ...   
95    1935631
96    1948565
97    1950267
98    1974109
99    1998768
Name: Estimated Salary, Length: 100, dtype: int64

In [ ]:
# to train the model we need traning data set and testing data set

In [ ]:
# splitting the dataset into traning and test sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)


In [ ]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [ ]:
x_test

array([[-1.7706028 , -0.70626767],
       [ 0.97004512, -0.19558446],
       [ 1.33065668, -1.34230282],
       [ 0.68155586, -0.55535608],
       [-0.76089041, -1.31600997],
       [ 0.46518892, -0.60838596],
       [-0.54452347, -0.19814173],
       [-1.19362429, -0.30878693],
       [ 0.82580049, -0.84044432],
       [-0.25603421,  1.6070083 ],
       [-0.11178959,  0.97934224],
       [-0.90513503,  1.19268159],
       [-0.90513503,  0.97604523],
       [-0.32815653,  0.86911836],
       [ 0.39306661, -1.47884895],
       [-0.11178959,  1.41621082],
       [ 1.11428974, -0.51352692],
       [-0.76089041,  1.13711241],
       [-1.2657466 , -1.14794377],
       [-0.76089041,  0.44080668]])

Fitting K-nn classifer to the traning data : Now we wil l fit the k nn classifier to the traning data . To do this we eill import the k neighbours classifier class of sklearn neighbour  library . After  importing the class , we will create the classifier object of the class . The parameter of this class will be:

- n_neighbours : To define the required neighbors of the alogirthm .Usally it takes 5
- metric = 'minkowski" This is the default parameter and itdecides the distance betwen the points
- p2 = It is equivalent to the standard Euclidean metric

In [ ]:
#Fitting KNN classifier ti the training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier.fit(x_train, y_train)


# To predict the test set result we will create a y_pred vector as we did in Logistic Regression. Below is the code for it:

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_test)
y_pred

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0])